### ISSUE TITLE
GitOpsCon NA 2024 CFP is open - update the banner

### ISSUE THREAD

**Issue by christianh814** [open-gitops/website#123]
The CFP for GitOpsCon NA 2024 is now open

https://sessionize.com/GitOpsCon-North-America-2024/

Can we get the banner updated?

![image](https://github.com/open-gitops/website/assets/10502863/c8adbeda-c5fc-4f58-8b11-22e76a58a02e)

Also, can we add it to the events page as well? (April 15th 2024, in seattle. Co-located with OpenSource Summit)

![image](https://github.com/open-gitops/website/assets/10502863/6c146d38-2e18-4c69-a66f-4bcaf6e283c2)

**Comment by varodrig** [comment]
it seems this is not longer needed since CFP are closed. @christianh814

**Comment by todaywasawesome** [comment]
Good call
