### ISSUE TITLE
404 in About page 🐞

### ISSUE THREAD

**Issue by ckavili** [open-gitops/website#15]
`charter` link is a 404 in About page :)

**Comment by ckavili** [comment]
By the way, is the goal to link this (and also some other 404s in Get Involved page) to related files under [gitops-working-group](https://github.com/gitops-working-group/gitops-working-group) repo or move them here like principles? 👀

**Comment by scottrigby** [comment]
Hey @ckavili 👋 Thanks for pointing this out! Should be fixed

- You're right, the goal is to https://github.com/open-gitops/project/issues/2
