### ISSUE TITLE
Ensure website follows CNCF website guidelines

### ISSUE THREAD

**Issue by caniszczyk** [open-gitops/website#32]
https://github.com/cncf/foundation/blob/master/website-guidelines.md

In particular, I see an issue with member list not being in alphabetical order.
<img width="1290" alt="Screen Shot 2021-08-16 at 9 34 30 AM" src="https://user-images.githubusercontent.com/63777/129580870-2b5c3ff1-22a0-43ac-b1b3-bb5a7627fe87.png">

Also having the LF Trademark footer is required and that's missing, see https://prometheus.io or https://kubernetes.io as an example.

**Comment by scottrigby** [comment]
✅

**Comment by christianh814** [comment]
I think we can close this now, right?

**Comment by scottrigby** [comment]
Yes thanks @christianh814 this was completed in August 👍 
And thanks @caniszczyk for the issue and direction earlier 🙏

**Comment by scottrigby** [comment]
Initial resolution for https://github.com/open-gitops/website/issues/22
