### ISSUE TITLE
Broken links on the website due to repository name changes

### ISSUE THREAD

**Issue by niklasmtj** [open-gitops/website#60]
Hey, everyone,

as mentioned in the meeting from 2022-02-02 there are a couple of links that link to the wrong location. This is probably because of the new repository structures. I checked the website for broken links and will give an overview which pages need a fix. I would love to prepare a PR for these links if I get the needed answers that are still open for me. 

## General
The GitHub Star button in the header still links to the old repo.  
**Is:** https://github.com/gitops-working-group/gitops-working-group  
**should be:** https://github.com/open-gitops/project  
Lines affected: [components/nav.js#L45](https://github.com/open-gitops/website/blob/73e18b363ee8a2daf734e25b2f55b5fef1812712/src/components/nav.js#L45) and [gatsby-config.json#L8](https://github.com/open-gitops/website/blob/73e18b363ee8a2daf734e25b2f55b5fef1812712/gatsby-config.js#L8)

The footer right now is: 
> 2022 © OpenGitOps. Overseen by the GitOps Working Group

GitOps Working Group still links to: https://github.com/gitops-working-group/gitops-working-group.
My question here is where this should link either https://github.com/open-gitops/project or https://github.com/cncf/tag-app-delivery ? Which one is the right one in this case since the initial work group will be sunsetted soon?
Line affected: [footer.js#L56](https://github.com/open-gitops/website/blob/73e18b363ee8a2daf734e25b2f55b5fef1812712/src/components/footer.js#L56)

## About page

The link to the charter also links to the old gitops-working-group charter.  
**Is:** https://github.com/gitops-working-group/gitops-working-group/blob/main/charter.md  
**Should be:** https://github.com/cncf/tag-app-delivery/blob/main/gitops-wg/charter.md
File affected: [content/pages/about.mdx](https://github.com/open-gitops/website/blob/main/content/pages/about.mdx)

The Press releases section has [three press releases](https://github.com/open-gitops/website/tree/main/content/press-releases) which only link to https://github.com/open-gitops. Are there press releases or should we disable / comment it out for the moment?

## Get Involved page
File affected: [content/pages/get-involved.mdx](https://github.com/open-gitops/website/blob/main/content/pages/get-involved.mdx)

The GitOps Working Group repository link is not yet updated and still links to the sunsetted repository:  
**Is:** https://github.com/gitops-working-group/gitops-working-group/   
**Should be:** https://github.com/cncf/tag-app-delivery/tree/main/gitops-wg

The Meetings link of the bi-weekly meeting section still links to the old location's `MEETINGS.md`. We have a Meetings section right under it.  
**Is:** https://github.com/gitops-working-group/gitops-working-group/blob/main/MEETINGS.md  
**Should be:** https://github.com/cncf/tag-app-delivery#meetings OR add a new `<h2 id="meetings">Meetings</h2>` and link to https://opengitops.dev/get-involved#Meetings ?

Like the other links the Committees section links to the old repository  
**Is:** https://github.com/gitops-working-group/gitops-working-group/blob/main/GOVERNANCE.md#committees  
**Should be:** https://github.com/open-gitops/project/blob/main/GOVERNANCE.md#committees

What I saw yesterday when I tried joining the Zoom call is that one needs an Zoom account to join the bi-weekly meeting. Maybe we could add a note to the link so future users don't get confused?

The links to the GitOps mailing list links to the [main repository's](https://github.com/cncf/tag-app-delivery) page. The mailing list however is at [https://lists.cncf.io/g/cncf-tag-app-delivery/topics](https://lists.cncf.io/g/cncf-tag-app-delivery/topics). So is this intended or would you like to change it for a direct link to the mailing list instead?

The last point I found is in the *get-involved/timeline* section at the [How to get involved](https://opengitops.dev/get-involved#how-to-get-involved ) link. This link does not have a target because the `<h2>` does not have an `id` attribute set.

That's everything I found. I'm open to feedback on how to implement the changes.

**Comment by chris-short** [comment]
Great work! If you want to create a PR to fix all this that'd be awesome. If you need help with that, let me know. If you don't have the time to implement fixes, this is a great first issue.

**Comment by niklasmtj** [comment]
Thanks, I already started implementing a couple of fixes. But there are still a couple of questions open for me which I mentioned above. Especially when there are two options to choose from. Once these are clear to me I will implement it and open the PR.
