### ISSUE TITLE
Update timeline on get involved page

### ISSUE THREAD

**Issue by todaywasawesome** [open-gitops/website#62]
This timeline is very out of date and missing a ton of information. 

https://opengitops.dev/get-involved

**Comment by scottrigby** [comment]
Agreed. The source is also outdated here https://github.com/cncf/tag-app-delivery/blob/main/gitops-wg/README.md#timeline

I think these should both be deduplicated by removing the events, and just keep to a timeline that doesn't include events – we have a "past events" section on the events page for that! https://opengitops.dev/events/

**Comment by strantalis** [comment]
@scottrigby I can work on cleaning this up. Is there anything else you want to be changed besides removing the duplicate events from the timeline?

**Comment by scottrigby** [comment]
@strantalis for this issue, no. This is a task to de-duplicate the events from the events tab on the website. A timeline is helpful just as the history of the WG, for context. But honestly I don't know why we want that on the website.

Ultimately we want to pull all this info from the website from canonical files in git. See
- https://github.com/open-gitops/website/issues/71

I personally think we have some work to do to clarify where the WG ends and the OpenGitOps project begins. This has come up in past meetings and is very much on our radar as a team. Our main focus now is on unblocking folks from contributing to the work products of the group - the lasting ones will like in the appropriate github.com/open-gitops project repos.

For this issue, perhaps the next steps should be:
1. Consolidate the necessary info onto https://github.com/open-gitops/.github/blob/main/CONTRIBUTING.md
2. pull in that contributing file automatically into the website, replacing the current get involved page (just make sure info is properly consolidated so we're not removing things that are important to help people get involved/contribute)

Then
3. rinse and repeat for the other pages on the website, pull from the respective canonical location of that info from git

**Comment by strantalis** [comment]
@scottrigby Ok I think that makes sense. So in this example we want to make sure what is on the [get-involved](https://github.com/open-gitops/website/blob/main/content/pages/get-involved.mdx) page is in sync with content we end up pulling dynamically from. 

I know @niklasmtj is working on #71 so I will follow up to see if there is anything I can help out with there. 

Also in pr #92 we removed the timeline from the get-involved page just so you are aware.

**Comment by todaywasawesome** [comment]
Timeline was removed so we can remove this.
