### ISSUE TITLE
Update events section to link to previous events

### ISSUE THREAD

**Issue by todaywasawesome** [open-gitops/website#63]
https://opengitops.dev/events shows past events but doesn't allow users to click to view recordings etc. This should be fixed.

**Comment by strantalis** [comment]
If this issue is still available to pick up, I can tackle it.

**Comment by christianh814** [comment]
/assign @strantalis 

Have at it!

**Comment by strantalis** [comment]
@christianh814 Couple questions.

1. Did you want to link to the current urls or should those be updated if the recordings are on youtube?

    **Example**: GitOpsCon NA 2021 currently points to https://events.linuxfoundation.org/gitopscon-north-america/ but recordings are hosted [here](https://www.youtube.com/watch?v=4gpomcM_sLE&list=PLj6h78yzYM2O_aoiru-ZeyVT0VHdWglfZ).

2. Did you want to use the same button that current events uses or something different?
![image](https://user-images.githubusercontent.com/18211470/154141663-538fdf71-04c1-420c-8e87-012f0164fd1d.png)
